### ISSUE TITLE
Fix: make the default focus on the plot widget

### ISSUE THREAD

**Issue by jurc192** [Plastic-Scanner/PSplot#12]
Now the keyboard-based workflow is not so smooth since pressing tab/space/enter triggers actions in other widgets instead of performing a scan. Figure out how to make plot/window focused by default, instead of individual widets.

**Comment by jurc192** [comment]
The commit 250510a partly solves the issue (plot widget is focused by default after starting the application), but as soon as you press a button the focus stays on a button. Would it be possible to "always" move focus back to the plot widget after pressing buttons? It seems convenient (for keyboard-based workflows) but I am not 100% how far to strecth this and if it is a smart idea in general. What happens when one wants to edit the table with keyboard, when to return focus back to widget?

**Comment by JoostScheffer** [comment]
Always focusing on the plot widget is possible.
But then indeed there arises a problem when one wants to select, for example, things in the table or the input or something else.
What can be done is implementing program-wide shortcuts for measuring, moving the graph etc,

**Comment by Jerzeek** [comment]
this no longer applies
